version: '3.4'

services:
  rabbit-mq:
    image: whitecastle77/rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - apigateway-network

  zipkinserver:
    image: whitecastle77/zipkin:2.23.2
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - apigateway-network

  mysqlserver:
    image: whitecastle77/mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 4Dmin123!
      MYSQL_DATABASE: books
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - apigateway-network

  namingserver:
    image: whitecastle77/namingserver:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    networks:
      - apigateway-network

  apigateway:
    image: whitecastle77/apigateway:0.0.1-SNAPSHOT
    ports:
      - 8700:8700
    depends_on:
      - namingserver
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8765/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkinserver:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - apigateway-network

  bookservice:
    image: whitecastle77/bookservice:0.0.1-SNAPSHOT
    restart: always
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8765/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkinserver:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://mysqlserver:3306/books?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 4Dmin123!
    ports:
      - 8000:8000
    depends_on:
      - namingserver
      - rabbit-mq
      - mysqlserver
    networks:
      - apigateway-network

  linkservice:
    image: whitecastle77/linkservice:0.0.1-SNAPSHOT
    restart: always
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://namingserver:8765/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkinserver:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8100:8100
    depends_on:
      - namingserver
      - rabbit-mq
      - bookservice
    networks:
      - apigateway-network

networks:
  apigateway-network:
    driver: bridge